### ISSUE TITLE
gulpfile.js   and main.js   error

### ISSUE THREAD

**Issue by lzdylan** [jcc/vue-laravel-example#1]
Error: Entry module not found: Error: Can't resolve 'buble' in 'E:\Vertrigo\www\laravel5'
resolve 'buble' in '

**Comment by jcc** [comment]
When did this problem arise?  Entry module not found. Your problem arose when you run the shell of 'npm install' with some error. You can try to delete the directory of 'node_modules' and install again.

**Comment by lzdylan** [comment]
Thank you, in the install NPM when the error of the newspaper, reinstall several times is a failure.
