### ISSUE TITLE
好像不行

### ISSUE THREAD

**Issue by void9main** [jcc/vue-laravel-example#10]
按照你readme上面的操作走一遍，显示不行
![image](https://user-images.githubusercontent.com/13297338/27001024-499fe030-4df2-11e7-86bc-65cc5e63a83d.png)

**Comment by jcc** [comment]
@void9main 请给出详细报错信息

**Comment by void9main** [comment]
我debug之后显示是这样
![image](https://user-images.githubusercontent.com/13297338/27001034-aff09ea6-4df2-11e7-8fac-23cc4932c3c3.png)
![image](https://user-images.githubusercontent.com/13297338/27001038-c79fc306-4df2-11e7-97f2-dae53d93d8b2.png)

**Comment by jcc** [comment]
@void9main 请你检查 Laravel 是否能正常运行....

**Comment by void9main** [comment]
laravel是正常的

**Comment by void9main** [comment]
给出的错误发现是缺少key值

**Comment by jcc** [comment]
@void9main Laravel 正常的？这就是 Laravel 的报错吖...你的 .env 的 APP_KEY 设置了？

**Comment by void9main** [comment]
加上这个php artisan key:generate命令已经解决
