### ISSUE TITLE
[问题] 路由的选择

### ISSUE THREAD

**Issue by xaclincoln** [jcc/vue-laravel-example#3]
你好.我是Laravel的新手，仔细地看了下代码，发现在main.j中启用了Vue Router。如果这样的话，是不是意味着在首页载入客户端后，就由Vue-Router接管路由，而Laravel仅提供WebApi给客户端使用？Laravel属于服务器端框架，VueJs不能在Php中进行原生的服务器端渲染，二者该如何结合使用？

**Comment by jcc** [comment]
是的，你需要在
Laravel 中写 Api 提供给 Vue 使用，你可以将后台使用前后端分离的方式，Vue Router 控制你后台访问的路由。
