### ISSUE TITLE
错误提示 Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by ghost** [jcc/vue-laravel-example#6]
Whoops, looks like something went wrong.

**Comment by jcc** [comment]
什么情况下会出现？

**Comment by ghost** [comment]
访问入口文件 http://localhost:8080/vue-laravel-example/public/index.php

**Comment by jcc** [comment]
请你阅读一下 [Laravel 官方文档](https://laravel.com) ，学习一下环境如何配置。

**Comment by chocopowwwa** [comment]
idk this is right or wrong but in my case,
changing gulpfile.js

```
require('laravel-elixir-vue')
```
to
```
require('laravel-elixir-vue-2')
```

kinda solve the issue

**Comment by jcc** [comment]
@chocopowwwa Thx, guy. Can you pull request for it?
