### ISSUE TITLE
路由失效？还有无法解析组件~

### ISSUE THREAD

**Issue by xlkit456852** [jcc/vue-laravel-example#7]
package.json一模一样，npm install、gulp成功
进入/example后，可看到App节点，但进入#/example后，页面还是停留在App节点，example节点没出现在App里，并且手动引入Example到App.vue里，Example标签被解释为< example >< / example>~没有效果~是还有哪个地方没配置好？

**Comment by jcc** [comment]
`#/example` 这是无效的，因为开启了 `history` 模式。你是怎么写的？手动引入Example到App.vue里

**Comment by xlkit456852** [comment]
哦！去掉history模式果然可以了~App.vue里原来是我写错了语法，现在可以引入了~感谢~
