### ISSUE TITLE
打包后在IE中运行，报错：不支持Object.assign方法

### ISSUE THREAD

**Issue by xlkit456852** [jcc/vue-laravel-example#9]
如题~在Chrome、火狐、360等浏览器均可，但IE中则报“对象不支持“assign”属性或方法”~应该如何解决？

**Comment by jcc** [comment]
[https://segmentfault.com/a/1190000006929961](https://segmentfault.com/a/1190000006929961)
[https://segmentfault.com/a/1190000006930013](https://segmentfault.com/a/1190000006930013)

你可以参考一下这两篇文章，`IE` 不支持 `Object.assign`.

[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill)
